### PR TITLE
Update Trajectories.version

### PR DESCRIPTION
**Pull request by skalou**
updated:
- "version"
- "KSP version"
- "ksp version max"
- and writed it in a more readable way: each thing has his own line ;)

### CODE REVIEW

**Comment by neuoy** [comment]
I'm not sure why you set KSP version and KSP version max to 2.0.0? You can't say the mod is guaranteed to work on version up to 2.0.0, can you? Or I don't understand what this is supposed to mean? (by the way, the version bug in 1.6.4 is not because the .version file was wrong, but because the one distributed in the zip file is the old one, so it's a packaging issue only). Your version is indeed more readable though :)

**Comment by skalou** [comment]
you title says it is compatible 1.2 :p, i just to try to help you and the community
[http://forum.kerbalspaceprogram.com/index.php?/topic/94368-120-trajectories-v164-2016-10-21-atmospheric-predictions/](url)
so the CKAN and this Github download are wrong version? ( both says 1..6.4 in the title but 1.6.3 in .version)

**Comment by neuoy** [comment]
Yes, it's compatible with 1.2, but not 2.0 that doesn't even exist? Or is it me that don't understand how the KSP version is supposed to be specified in that file?

As I said, the .version file IS wrong in the released zip file, and I'm aware of that, but it was right in github already. It's just that the previous file ended up being zipped in the release, instead of the latest github file (so basically, the bug is already fixed, and the next release will solve the issue).

Thanks for the reformatting though, I'll keep that.

**Comment by skalou** [comment]
oups, mistake! yes you are right it's 1.2 :/

**Pull request merged**
