### PR TITLE
Added API

### PR DESCRIPTION
**Pull request by CalebJ2**
Added fairly basic `public static class API` with public methods `getImpactPosition()`, `plannedDirection()`, `correctedDirection()`, and `setTarget(lat,lon,alt)`.

Only works for the active vessel.

Have any thoughts or suggestions?

### CODE REVIEW

**Comment by neuoy** [comment]
Sorry, I read that but then forgot about it.
That looks good, especially if it provides the features you need for kOS. However, maybe you could reuse the currently computed impact point, instead of computing the whole trajectory each time? In current implementation, trajectory computation is spread over multiple frames to avoid using too much CPU time. Since you apparently only need the current vessel impact point, maybe you could use the last computed one?

**Comment by CalebJ2** [comment]
That would be good, but I think the impact point is only updated while in map view. Maybe it could always be updating? Or maybe there could be a flag the API could set. What do you think is the best way?

**Comment by CalebJ2** [comment]
Added a setting that the API can set that allows trajectory updates outside of mapview. Now it doesn't force updates.

**Comment by neuoy** [comment]
Hi,

Sorry for the late reply.

Your code seems fine, and I just wonder if it's a good idea to store the new flag in the settings. How do you intend to use it? Would you enable it in your kOS script each time, or does it need to be persisted in game saves? I see two possible issues if this is not handled correctly: your script could be in an incoherent state where it expects the flag to be set but it is not (because for example you reloaded a save) ; or the flag could remain set forever even after the script has finished for a long time. But if you don't see these points as problematic, I can just merge now (after all, players that use the flag would be aware of possible performance impact, and responsible for their scripts consistency if reloading a save game)

**Pull request merged**
