### PR TITLE
Switch to OpenGL drawing for in-flight trajectory lines

### PR DESCRIPTION
**Pull request by fat-lobyte**
This patch does away with the drawing of lines using the LineRenderer and the drawing of the Targeting cross using a texture.

The result should look like this:

lrchs92

The reason for replacing the LineRenderer Object is that the LineRenderer line width is dependend on the viewing distance, which makes the line too thin to see in the distance.

The new line is rendered as 1 pixel wide. This is very thin, but unfortunately I'm not sure how to draw this line wider ([GL.Quads](https://docs.unity3d.com/ScriptReference/GL.QUADS.html) is a starting point).

The reason for replacing the AimingCross is that the new cross is much better visible from the distance, and does not need a collider (and hence isn't rendered on the ship), but does not disappear under the terrain. The drawback is that when the cross is close and the corners of the cross triangles go behind the camera, slight graphic glitches will happen.

Note that the GLUtils code was stolen (with permission) from MechJeb, thanks to sarbian.

Please review this code and give feedback!

### CODE REVIEW

**Comment by PiezPiedPy** [comment]
Nice touch ;)

I've had a quick scan through the code and it looks fine to me.

How about changing the size of the cursor so it gets smaller as the camera gets closer, don't know how you would achieve that though but it might also help with the glitches.

**Comment by fat-lobyte** [comment]
> I've had a quick scan through the code and it looks fine to me.

Thanks!

> How about changing the size of the cursor so it gets smaller as the camera gets closer, don't know how you would achieve that though but it might also help with the glitches.

Sorry, I just really don't know how.

I have experimented with 4 different ways to draw lines on the screen. None of them is perfect:
1. `LineRenderer`: simple enough, but crashes the game and makes the lines too thin to see in the distance
2. Vectrosity: Coordinates are FUBAR. I'm clearly getting *something* on the screen that resembles a trajectory, but I have tried like 5 different coordinate systems. I think KSP itself does something very strange to it that makes it unusable for mods
3. GL: very cumbersome and too low level. Since I'm not a game dev, I just plainly don't understand it.
4. With `MeshRenderer`, as is done currently in the Map View. I tried to port the code and plainly failed, couldn't get anything to show up in the flight screen.


BTW, I can tell you exactly why the glitches occur:
`Camera.WorldToViewportPoint()` turns world coordinates into "viewport" coordinates that go from [-1;+1] for x, y. Here, negative numbers mean that they are off the screen and should not be rendered.
`GL.Vertex3()` takes viewport coordinates, but doesn't like negative numbers at all - and resorts to "undefined behaviour". I tried clamping, I tried `Abs`ing but none of that really makes it better.

I would have to rewrite big chunks of the grafted GLUtils code, which is just way above my pay grade and does not seem worth the effort. Might be better to invest the time into understanding how MapOverlay.cs works and to port it to FlightOverlay.cs (and just merging it).

**Comment by PiezPiedPy** [comment]
Might be better to get to grips with MapOverlay.cs but it might fail when it comes to rendering the cross on the ground. I've not looked at MapOverlay.cs yet so I have no idea how the rendering is done or if it would be suitable
I can have a good look at it when I've been through the gui, I've worked on 3D engine code before so I shouldn't have to much problem with it apart from I'm new with Unity ;)
As for the cursor size it can probably be changed by resizing the texture, not sure, worse case will be to write a new shader.

**Comment by fat-lobyte** [comment]
> I can have a good look at it when I've been through the gui, I've worked on 3D engine code before so I shouldn't have to much problem with it apart from I'm new with Unity ;)

I think you should focus on the GUI for now, what happens after that - we'll see ;)

> As for the cursor size it can probably be changed by resizing the texture, not sure, worse case will be to write a new shader.

Wow, a new shader, huh? Let's not get carried away because as useful as this might be, we have more pressing issues. Except if you are having fun doing that - then by all means get carried away ;)

I think for all the remaining issues, I will still merge this this PR. It's an improvement over the previous method and we can fix the issues at a later point in time.

**Comment by PiezPiedPy** [comment]
>I think for all the remaining issues, I will still merge this this PR. It's an improvement over the previous method and we can fix the issues at a later point in time.

small improvements are better than none and it will be nice to have the more stable target sprite you've created.

**Pull request merged**
