### PR TITLE
Changed Profiler to use KSP's PopupDialog class

### PR DESCRIPTION
**Pull request by PiezPiedPy**
The Profiler GUI has been updated to use KSP's PopupDialog class which in turn uses a GameObject with a canvas and also has the added benefit of stopping most mouse click through events, even to the context menus :)

One drawback though is I cant stop clicks getting through to the manoeuvre nodes on the map view >.<

Also changed some comments to summaries and added {get; } to some methods in the Utils.cs file.

I'm thinking using KSP's Dialog class could be a way for the main Trajectories window to be displayed, as it seems to have the functionality we need.

### CODE REVIEW

**Comment by fat-lobyte** [comment]
Thanks a lot, I really like this profiler!

Does this mean that your are getting proficient with the Canvas/PopupDialog system, and we can look forward to a new GUI for Trajectories? ;)

**Comment by PiezPiedPy** [comment]
That's the general idea, hope it works :)

**Comment by PiezPiedPy** [comment]
If you want to follow how I'm progressing with a new Gui you can follow my branch [NewGui-Test](https://github.com/PiezPiedPy/KSPTrajectories/commits/NewGui-Test), I'm also including code for the new Localization system.

**Comment by fat-lobyte** [comment]
> If you want to follow how I'm progressing with a new Gui you can follow my branch NewGui-Test, I'm also including code for the new Localization system.

Yay, looking forward to it!

I would also quite like to discuss the GUI, because I'm not entirely happy with how it looks now. Are you OK with discussing it on the dev thread here:

http://forum.kerbalspaceprogram.com/index.php?/topic/94370-13

If possible, could you post screenshots or mock-ups there, so we can discuss it?

**Comment by PiezPiedPy** [comment]
Sounds like a good idea ;)

**Pull request merged**
