### PR TITLE
Stop GUI Click through

### PR DESCRIPTION
**Pull request by PiezPiedPy**
Made a start on stopping GUI click through.

### CODE REVIEW

**Comment by PiezPiedPy** [comment]
Going to attempt to stop the context menu click through next but it's proving to be a bit harder than expected, I'll fix it if it kills me lol

**Comment by fat-lobyte** [comment]
> Going to attempt to stop the context menu click through next but it's proving to be a bit harder than expected, I'll fix it if it kills me lol

Haha, so should I hold off on merging until you've solved it?

**Comment by PiezPiedPy** [comment]
Might as well but if I don't get it sorted by the next release you can merge it then if you want.

**Comment by fat-lobyte** [comment]
> Might as well but if I don't get it sorted by the next release you can merge it then if you want.

Sounds good! Just keep it mergable.

Mind you, I'll be on vacation for a week, so I will probably not reply ;)

**Comment by PiezPiedPy** [comment]
I'll use another branch for testing to keep this one clean, have a happy holiday ;)

**Comment by PiezPiedPy** [comment]
Turned the Camera controls back on, was a bit annoying when moving the camera about and then it stopping when the mouse moved over the Trajectories window.

**Comment by fat-lobyte** [comment]
Hey, so I don't know if I understand the feature wrong or if I compiled it wrong, but the patch doesn't stop click-through for me. I can still toggle that SAS/RCS buttons on the NavBall or the Escape-Menu *through* the Trajectories window. Is that supposed to happen?

**Comment by PiezPiedPy** [comment]
I've found that if certain objects (SAS, RCS, Throttle etc) are input locked when the cursor is over a GUI window, then they will not respond to keyboard events. I decided to leave them unlocked so as to not inadvertently cut off control to the user.

SAS, RCS can be disabled easily by adding **'ControlTypes.SAS | ControlTypes.RCS'** to the Input Lock variable **FlightLockTypes** on Line49 in File *'MapGUI.cs'*.
Other ControlTypes can be added just as easily ;)

**Comment by fat-lobyte** [comment]
Ah ok, I understand now. Well if you think that's a good locking policy, then lets do it.

**Comment by PiezPiedPy** [comment]
I'm fine with how it is, fire away.

**Comment by fat-lobyte** [comment]
@PiezPiedPy 

Sorry to annoy you about this, but to me it seems that there are no input locks at all, not only for RCS/SAS as discussed, but also for *any* of the stock GUI components, like the time display, the staging menu, the "top bar thingy" (with buttons close to the altimeter).

I think if we already have the supporting code, we should also lock those out if the window is overlapping those controls.

Is there really no way of blocking clicks, without also blocking the keyboard input?

**Comment by PiezPiedPy** [comment]
The InputLockManager class that KSP uses locks both mouse and keyboard, I have not seen a method inside it that we could use to only disable the mouse.

I also tried catching the mouse click event but the game processed the click no matter what I tried to stop it. even event.use did not work :/

Regardless, turning on and off specific inputs is just a case of adding or removing the required ControlTypes.enum to the FlightLockTypes field on Line49 in File 'MapGUI.cs'

But..
What I have found out so far is the problem is to do with the way Unity handles Gui popup windows, they are only meant for debug I/O while developing a game on Unity so have limited functionality.

In-game menus as such should be in there own Game object and using the canvas system etc.

Using the Gui and InputLockManager is more of a hacky way to disable mouse input.

Apparently there is a class called a raycaster that can be used somehow to catch mouse inputs when the mouse is over a certain Game object but I am not to sure if it is an old method and if the functionality of it has been moved to the canvas system, more research is needed.

 I think changing to the canvas system will be better,
   so I have been looking at how the canvas system works with a game object and a way to implement the changes needed to stop the mouse input but Unity is pretty new to me, I'm learning though ;)

**Comment by PiezPiedPy** [comment]
Have a mess about with the FlightLockTypes field on Line49 in File 'MapGUI.cs' ;)

**Comment by fat-lobyte** [comment]
If that's so complicated, we should definitely not force the input locks or mess with any kind of raycasting or something.

Do I understand correctly that the "canvas system" is the right way to do GUIs in KSP? Would that require a whole GUI rewrite?

**Comment by PiezPiedPy** [comment]
Correct but there is only one small window, so I cant see it being to difficult once I lean the mechanics of how the canvas works.

**Comment by fat-lobyte** [comment]
I mean on one hand, I would be super happy if we got a new GUI system based on canvases. But when I browse through DStaal's instructions [here](http://forum.kerbalspaceprogram.com/index.php?/topic/151354-unity-ui-creation-tutorial/), it seems that it's quite a bit of work to get it to run.

**Pull request merged**
