### PR TITLE
Update Module Manager to v2.8.0

### PR DESCRIPTION
**Pull request by PiezPiedPy**
Getting ready for KSP v1.3

On a side note, do we really need MM, as there are no .cfg patch files used in Trajectories.
Maybe it should be removed, unless a part is added in the future to enable Trajectories features, just like KER has its little chip you have to include on ships.

### CODE REVIEW

**Comment by neuoy** [comment]
Actually, you should have a .cfg file, which adds a module to all command parts (capsule, etc.) which is used to store Trajectories settings (angle of attack, target, etc.) per craft, and persist them when saving the game. If a craft has multiple command parts, settings are duplicated in all parts so that all sub-crafts have them in case they separate (e.g. after staging).

**Comment by PiezPiedPy** [comment]
Ooops my bad (I'll just go and hide in a corner). Spotted the .cfg file ;)

**Comment by neuoy** [comment]
no problem :) I did hesitate at the time I introduced the MM dependency, just for persisting a few properties... maybe there is a better way, I don't know. By the way, feel free to ask questions of something seems obscure (and some things probably are).

**Comment by fat-lobyte** [comment]
Another way would be a SCENARIO in the persistance file or just a local config file in the Trajectories Plugin directory, but those would not be vessel-specific.

Personally, I don't have a problem with that, but I don't know how the users see that.

**Pull request merged**
